image: docker.io/cytopia/ansible:latest-tools

stages:
- prepare
- deploy

variables:
  ANSIBLE_CONFIG: ${CI_PROJECT_DIR}/deploy/ansible.cfg
  ANSIBLE_ROOT: ${CI_PROJECT_DIR}/deploy/
 
cache:
  paths:

validate:
  stage: prepare
  image: docker.io/cytopia/ansible-lint:5
  script:
    - ansible-lint -v --show-relpath --parseable-severity --nocolor ${ANSIBLE_ROOT}/deploy.yml 

deploy_preview:
  stage: deploy
  image: docker.io/cytopia/ansible:latest-tools
  before_script:
    - python -V # Print out python version for debugging

    # Install dependencies
    # - pip install -r requirements.txt
    # - ansible-galaxy install -r requirements.yml
      
    # Setup SSH-Agent using private key from CI/CD variable
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - chmod 400 "$ansible_private_key"
    - eval $(ssh-agent -s)
    - ssh-add "$ansible_private_key" 
  script:
  - ansible-playbook ${ANSIBLE_ROOT}/deploy.yml -v -e GIT_SSH_KEY=$git_ssh_key --extra-vars "@${ANSIBLE_ROOT}/vars_preview.yml"  
  only:
  - develop

deploy_prod:
  stage: deploy
  image: docker.io/cytopia/ansible:latest-tools
  before_script:
    - python -V # Print out python version for debugging

    # Install dependencies
    # - pip install -r requirements.txt
    # - ansible-galaxy install -r requirements.yml
      
    # Setup SSH-Agent using private key from CI/CD variable
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - chmod 400 "$ansible_private_key"
    - eval $(ssh-agent -s)
    - ssh-add "$ansible_private_key" 
  script:
  - ansible-playbook ${ANSIBLE_ROOT}/deploy.yml -v -e GIT_SSH_KEY=$git_ssh_key --extra-vars "@${ANSIBLE_ROOT}/vars_prod.yml"
  only:
  - master
  allow_failure: false