---
- name: JS-Buchsi Website Deployment
  hosts: all
  vars: # all variables used to deploy are defined here
    WEBROOT: "/home/clients/625287d9edbd32bee10d3b5946921928/sites/js-buchsi.ch/preview"
    SOURCE_BRANCH: "develop"
    GIT_USER: "sammy"
    GIT_PASS: "superSecure"
  tasks:
  - name: Sync files to {{ SOURCE_BRANCH }} version
    git:
      repo: "https://{{ GIT_USER }}:{{ GIT_PASS }}@code.immerda.ch/technat/js-buchsi.ch.git"
      dest: "{{ WEBROOT }}"
      single_branch: yes
      update: yes
      recursive: yes
      version: "{{ SOURCE_BRANCH }}"
